general:
  min_severity: Info
  verbose: false
  quiet: false
  include_patterns:
  - '**/*.sol'
  exclude_patterns:
  - '**/node_modules/**'
  - '**/test/**'
  - '**/tests/**'
  - '**/.git/**'
  max_file_size: 10485760
detectors:
  min_severity: Info
  min_confidence: Low
  enabled_categories: []
  disabled_detectors: []
  enabled_detectors: []
  detector_timeout: 30
  fail_fast: false
  custom_settings: {}
cache:
  enabled: true
  max_memory_mb: 256
  max_entries: 10000
  cache_dir: null
  persistent: true
  ttl_hours: 1
output:
  format: console
  colors: true
  show_fixes: true
  show_snippets: true
  snippet_lines: 3
  sort_by_severity: true
performance:
  max_threads: 8
  parallel_analysis: true
  batch_size: 10
  memory_limit_mb: 512
